### PR TITLE
Merge code from the Cherry Trail used.

### PR DESCRIPTION
**Pull request by tanminger**
Jira: None.
Test: Test on Joule.

Signed-off-by: tanminger <ming.tan@intel.com>

### CODE REVIEW

**Comment by tpalli** [comment]
What is the benefit of merging this code, what additional value? Who is the user for this? How was this additional functionality tested?

**Comment by tanminger** [comment]
The boot loader kernelflinger need sign-efi-sig-list to sign the oemvar.
Current old code even can’t be compiled since the openssl directory is changed.
This code is copied from Intel modified code for Cherry Trail. With many bug fix and improvement. And tested when boot loader for Cherry Trail released.

Thank you.
Tan Ming.

**Comment by tpalli** [comment]
OK, thanks for the information! Please in the future, always explain the purpose (bugfix, new functionality) in the commit message. This way later it's easier to find out why some of the changes were made from git log.

**Comment by kalyankondapally** [comment]
@tanminger Can you update commit message with what u just commented here

**Comment by tanminger** [comment]
Update the commit message.

**Pull request closed without merging**
